[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
stablecoin_contract = "3gz13a5Pt9gjADuu4S8aEtaDBEjzKv15vrYjPMuNmqFW"

[programs.localnet]
stablecoin_contract = "3gz13a5Pt9gjADuu4S8aEtaDBEjzKv15vrYjPMuNmqFW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/whitehorse/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
